// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Phoneword
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int CallButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int PhoneNumberText = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int TranslateButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int Call = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int Enter = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Number = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Translate = 2130968576;
			
			private String()
			{
			}
		}
	}
}
