// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Corpy
{
	public partial class EmployeeViewController : UIViewController
	{
		Employee detailItem;
		
		public Employee DetailItem {
			get {
				return detailItem;
			}
			set {
				detailItem = value;
				if (IsViewLoaded)
					ConfigureView ();
			}
		}
		void ConfigureView ()
		{
			// Update the user interface for the detail item
			if (DetailItem != null) {
				NameLabel.Text = detailItem.NameFormatted;
			//	DepartmentLabel.Text = detailItem.Department;
			}
		}


		public EmployeeViewController (IntPtr handle) : base (handle)
		{
		}
	
		#region View lifecycle
		
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			
			// Perform any additional setup after loading the view, typically from a nib.
			ConfigureView();
		}
		
		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();
			
			// Clear any references to subviews of the main view in order to
			// allow the Garbage Collector to collect them sooner.
			//
			// e.g. myOutlet.Dispose (); myOutlet = null;
			
			ReleaseDesignerOutlets ();
		}
		
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
		}
		
		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
		}
		
		public override void ViewWillDisappear (bool animated)
		{
			base.ViewWillDisappear (animated);
		}
		
		public override void ViewDidDisappear (bool animated)
		{
			base.ViewDidDisappear (animated);
		}
		
		#endregion
	}
}