// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using Foundation;
using UIKit;
using AVFoundation;

namespace StoryboardTables
{
	public partial class TaskDetailViewController : UITableViewController
	{
		Task currentTask {get;set;}
		public RootViewController Delegate {get;set;}

		public TaskDetailViewController (IntPtr handle) : base (handle)
		{

		}
		
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			SaveButton.TouchUpInside += (sender, e) => {
				currentTask.Name = TitleText.Text;
				currentTask.Notes = NotesText.Text;
				currentTask.Done = DoneSwitch.On;
				Delegate.SaveTask(currentTask);
			};
			DeleteButton.TouchUpInside += (sender, e) => {
				Delegate.DeleteTask(currentTask);
			};

			if (UIDevice.CurrentDevice.CheckSystemVersion (7, 0)) {
				// requires iOS 7
				SpeakButton.TouchUpInside += (sender, e) => {
					Speak (TitleText.Text + ". " + NotesText.Text);
				};
//				InitPitchAndVolume ();
			} else {
				SpeakButton.SetTitleColor (UIColor.Gray, UIControlState.Disabled);
				SpeakButton.Enabled = false;
			}
		}

		// this will be called before the view is displayed 
		public void SetTask (RootViewController d, Task task) {
			Delegate = d;
			currentTask = task;
		}
		// when displaying, set-up the properties
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			TitleText.Text = currentTask.Name;
			NotesText.Text = currentTask.Notes;
			DoneSwitch.On = currentTask.Done;
		}

		/// <summary>
		/// Speak example from: 
		/// http://blog.xamarin.com/make-your-ios-7-app-speak/
		/// </summary>
		void Speak (string text)
		{
			var speechSynthesizer = new AVSpeechSynthesizer ();

//			var voices = AVSpeechSynthesisVoice.GetSpeechVoices ();

			var speechUtterance = new AVSpeechUtterance (text) {
				Rate = AVSpeechUtterance.MaximumSpeechRate/4,
				Voice = AVSpeechSynthesisVoice.FromLanguage ("en-AU"),
				Volume = volume,
				PitchMultiplier = pitch
			};

			speechSynthesizer.SpeakUtterance (speechUtterance);
		}

		float volume = 0.5f;
		float pitch = 1.0f;
		// http://blog.xamarin.com/make-your-ios-7-app-speak/
//		void InitPitchAndVolume ()
//		{
//			volumeSlider.MinValue = 0;
//			volumeSlider.MaxValue = 1.0f;
//			volumeSlider.SetValue (volume, false);
//
//			pitchSlider.MinValue = 0.5f;
//			pitchSlider.MaxValue = 2.0f;
//			pitchSlider.SetValue (pitch, false);
//
//			volumeSlider.ValueChanged += (sender, e) => {
//				volume = volumeSlider.Value;
//			};
//
//			pitchSlider.ValueChanged += (sender, e) => {
//				pitch = volumeSlider.Value;
//			};
//		}

	}
}