// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.AVFoundation;
using NDCPortable;
using System.Threading.Tasks;

namespace iOSTodo
{
	public partial class TaskDetailViewController : UITableViewController
	{
		TodoItem currentTodoItem {get;set;}
		public RootViewController Delegate {get;set;}

		public TaskDetailViewController (IntPtr handle) : base (handle)
		{

		}
		
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			SaveButton.TouchUpInside += (sender, e) => {
				currentTodoItem.Name = TitleText.Text;
				currentTodoItem.Notes = NotesText.Text;
				currentTodoItem.Done = DoneSwitch.On;
				AppDelegate.Current.TaskMgr.SaveTask(currentTodoItem);
				NavigationController.PopViewControllerAnimated(true);
			};
			DeleteButton.TouchUpInside += (sender, e) => {
				AppDelegate.Current.TaskMgr.DeleteTask(currentTodoItem);
				NavigationController.PopViewControllerAnimated(true);
			};

			if (UIDevice.CurrentDevice.CheckSystemVersion (7, 0)) {
				// requires iOS 7
				SpeakButton.TouchUpInside += (sender, e) => {
					Speak (TitleText.Text + ". " + NotesText.Text);
				};
			} else {
				SpeakButton.SetTitleColor (UIColor.Gray, UIControlState.Disabled);
				SpeakButton.Enabled = false;
			}
		}

		// this will be called before the view is displayed 
		public void SetTask (TodoItem todo) {
			currentTodoItem = todo;
		}
		// when displaying, set-up the properties
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			TitleText.Text = currentTodoItem.Name;
			NotesText.Text = currentTodoItem.Notes;
			DoneSwitch.On = currentTodoItem.Done;
		}

		float volume = 0.5f;
		float pitch = 1.0f;
		/// <summary>
		/// Speak example from: 
		/// http://blog.xamarin.com/make-your-ios-7-app-speak/
		/// </summary>
		void Speak (string text)
		{
			var speechSynthesizer = new AVSpeechSynthesizer ();

			var speechUtterance = new AVSpeechUtterance (text) {
				Rate = AVSpeechUtterance.MaximumSpeechRate/4,
				Voice = AVSpeechSynthesisVoice.FromLanguage ("en-AU"),
				Volume = volume,
				PitchMultiplier = pitch
			};

			speechSynthesizer.SpeakUtterance (speechUtterance);
		}
	}
}