// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardTables
{
	public partial class TaskViewController : UIViewController
	{
		public TaskViewController (IntPtr handle) : base (handle)
		{
		}

		public Task currentTask { get; set; }

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SaveButton.TouchUpInside += (sender, e) => {
				// retrieve data from UIneed 
				currentTask.Title = TitleText.Text;
				currentTask.Done = DoneSwitch.On;

				var vm = new TaskViewModel();
				currentTask.Id = vm.Save (currentTask); // unnecessary

				NavigationController.PopToRootViewController (true);
			};

			CancelButton.TouchUpInside += (sender, e) => {
				NavigationController.PopToRootViewController (true);
			};
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);

			// bind data to UI
			TitleText.Text = currentTask.Title;
			DoneSwitch.On = currentTask.Done;
		}
	}
}
